Feature/chalk to magic
WillowgastWebOfCode/MagicCircleGame pull request #10
Opened 2022-10-03 18:02 UTC by artart92

Implemented a start to converting chalk drawings to magic objects.

Changed magic circle initialisation to use the PVector 3d capability.

Changed update method of the MagicCircle class to push and pop matrix to fix the rotation draw bug.

2022-10-04 18:29 UTC, WillowgastWebOfCode commented on Processing/magicCircle.pde
> +    pushMatrix();
draw() could perhaps do the same thing as push and popping matrixes. Try that for a moment.

2022-10-04 18:37 UTC, WillowgastWebOfCode requested changes
Try draw() and store the elipse variables with more context.

2022-10-09 15:07 UTC, artart92 commented
Using draw() could not replace the push and pop matrix functions.

2022-10-09 15:13 UTC, WillowgastWebOfCode approved these changes

2022-10-09 15:13 UTC, merged